/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form.pembayaran;

/**
 *
 * @author rpl
 */
public class form_menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form form_menu_utama
     */
    public form_menu_utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbbiodata = new javax.swing.JButton();
        jbjurusan = new javax.swing.JButton();
        jbuser = new javax.swing.JButton();
        jbkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbbiodata.setText("BIODATA");
        jbbiodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbiodataActionPerformed(evt);
            }
        });
        getContentPane().add(jbbiodata, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jbjurusan.setText("JURUSAN");
        jbjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbjurusanActionPerformed(evt);
            }
        });
        getContentPane().add(jbjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jbuser.setText("USER");
        jbuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuserActionPerformed(evt);
            }
        });
        getContentPane().add(jbuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 130, 80, -1));

        jbkeluar.setText("KELUAR");
        jbkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jbkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbbiodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbiodataActionPerformed
        // TODO add your handling code here:
        new form_biodata().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbbiodataActionPerformed

    private void jbjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbjurusanActionPerformed
        // TODO add your handling code here:
         new form_jurusan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbjurusanActionPerformed

    private void jbuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuserActionPerformed
        // TODO add your handling code here:
         new form_user().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbuserActionPerformed

    private void jbkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbbiodata;
    public javax.swing.JButton jbjurusan;
    public javax.swing.JButton jbkeluar;
    public javax.swing.JButton jbuser;
    // End of variables declaration//GEN-END:variables
}
