/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form.pembayaran;
import com.code.pembayaran.code_biodata;

/**
 *
 * @author rpl
 */
public class form_biodata extends javax.swing.JFrame {

    /**
     * Creates new form form_biodata
     */
    public form_biodata() {
        initComponents();
        new code_biodata().bersih(this);
        new code_biodata().kunci(this);
        new code_biodata().tampildata(this);
        new code_biodata().tampil_jurusan(this);
        new code_biodata().cari_data(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtnis = new javax.swing.JTextField();
        jtnama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtalamat = new javax.swing.JTextArea();
        jtnotelfon = new javax.swing.JTextField();
        jcjeniskelamin = new javax.swing.JComboBox<>();
        jckdjurusan = new javax.swing.JComboBox<>();
        jbtambah = new javax.swing.JButton();
        jbubah = new javax.swing.JButton();
        jbhapus = new javax.swing.JButton();
        jbsimpan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtablebiodata = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jtcarinis = new javax.swing.JTextField();
        jbclose = new javax.swing.JButton();
        jbcari = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NIS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setText("No Telfon");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel6.setText("KD Jurusan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setText("BIODATA SISWA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jtnis.setText("jTextField1");
        getContentPane().add(jtnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, -1));

        jtnama.setText("jTextField2");
        getContentPane().add(jtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 150, -1));

        jtalamat.setColumns(20);
        jtalamat.setRows(5);
        jScrollPane2.setViewportView(jtalamat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 190, 100));

        jtnotelfon.setText("jTextField3");
        getContentPane().add(jtnotelfon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 160, -1));

        jcjeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilihan -", "pria", "wanita" }));
        getContentPane().add(jcjeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 100, -1));

        jckdjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jckdjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 100, -1));

        jbtambah.setText("Tambah");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });
        getContentPane().add(jbtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jbubah.setText("Ubah");
        jbubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbubahActionPerformed(evt);
            }
        });
        getContentPane().add(jbubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jbhapus.setText("Hapus");
        jbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhapusActionPerformed(evt);
            }
        });
        getContentPane().add(jbhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jbsimpan.setText("Simpan");
        jbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jbsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jtablebiodata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablebiodata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablebiodataMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtablebiodata);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 410, 110));

        jLabel8.setText("Cari NIS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jtcarinis.setText("jTextField4");
        jtcarinis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcarinisActionPerformed(evt);
            }
        });
        getContentPane().add(jtcarinis, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 130, 20));

        jbclose.setText("Close");
        jbclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcloseActionPerformed(evt);
            }
        });
        getContentPane().add(jbclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jbcari.setText("cari");
        jbcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcariActionPerformed(evt);
            }
        });
        getContentPane().add(jbcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcloseActionPerformed
        // TODO add your handling code here:
        new form_menu_utama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbcloseActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
        // TODO add your handling code here:
        new code_biodata().bersih(this);
        new code_biodata().buka_kunci(this);
         new code_biodata().tampildata(this);
        jbubah.setEnabled(false);
        jbhapus.setEnabled(false);
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsimpanActionPerformed
          // TODO add your handling code here:
           new code_biodata().simpan(this);
           new code_biodata().bersih(this);
    }//GEN-LAST:event_jbsimpanActionPerformed

    private void jtcarinisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcarinisActionPerformed
        // TODO add your handling code here:
           new code_biodata().cari_data(this);
           new code_biodata().buka_kunci(this);
           jbubah.setEnabled(true);
           jbhapus.setEnabled(true);
           jbsimpan.setEnabled(false);
    }//GEN-LAST:event_jtcarinisActionPerformed

    private void jbcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcariActionPerformed
        // TODO add your handling code here:
           new code_biodata().cari_data(this);
           new code_biodata().buka_kunci(this);
    }//GEN-LAST:event_jbcariActionPerformed

    private void jtablebiodataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablebiodataMouseClicked
        // TODO add your handling code here:
        new code_biodata().klik_table(this);
        new code_biodata().buka_kunci(this);
        jbsimpan.setEnabled(false);
                
    }//GEN-LAST:event_jtablebiodataMouseClicked

    private void jbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhapusActionPerformed
        // TODO add your handling code here:
          new code_biodata().hapus(this);
    }//GEN-LAST:event_jbhapusActionPerformed

    private void jbubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbubahActionPerformed
        // TODO add your handling code here:
        new code_biodata().ubah(this);
    }//GEN-LAST:event_jbubahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_biodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbcari;
    private javax.swing.JButton jbclose;
    public javax.swing.JButton jbhapus;
    public javax.swing.JButton jbsimpan;
    public javax.swing.JButton jbtambah;
    public javax.swing.JButton jbubah;
    public javax.swing.JComboBox<String> jcjeniskelamin;
    public javax.swing.JComboBox<String> jckdjurusan;
    public javax.swing.JTable jtablebiodata;
    public javax.swing.JTextArea jtalamat;
    public javax.swing.JTextField jtcarinis;
    public javax.swing.JTextField jtnama;
    public javax.swing.JTextField jtnis;
    public javax.swing.JTextField jtnotelfon;
    // End of variables declaration//GEN-END:variables
}
