/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form.pembayaran;
import com.code.pembayaran.code_biodata;
import com.code.pembayaran.code_jurusan;
/**
 *
 * @author rpl
 */
public class form_jurusan extends javax.swing.JFrame {

    /**
     * Creates new form form_jurusan
     */
    public form_jurusan() {
        initComponents();
        new code_jurusan().kunci(this);
        new code_jurusan().bersih(this);
        new code_jurusan().tampildata(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtambah = new javax.swing.JButton();
        jbubah = new javax.swing.JButton();
        jbhapus = new javax.swing.JButton();
        jbsimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtablejurusan = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jtkdjurusan = new javax.swing.JTextField();
        jtnamajurusan = new javax.swing.JTextField();
        jtketuajurusan = new javax.swing.JTextField();
        jtjmlkelas = new javax.swing.JTextField();
        jtcarikdjurusan = new javax.swing.JTextField();
        jbclose = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("JURUSAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 150, -1));

        jLabel2.setText("KD Jurusan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel3.setText("Nama Jurusan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel4.setText("Ketua Jurusan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel5.setText("Jml Kelas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jbtambah.setText("Tambah");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });
        getContentPane().add(jbtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jbubah.setText("Ubah");
        getContentPane().add(jbubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jbhapus.setText("Hapus");
        getContentPane().add(jbhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jbsimpan.setText("Simpan");
        jbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jbsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jtablejurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtablejurusan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 350, 150));

        jLabel6.setText("Cari KD Jurusn");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, 10));

        jtkdjurusan.setText("jTextField1");
        getContentPane().add(jtkdjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 110, -1));

        jtnamajurusan.setText("jTextField2");
        getContentPane().add(jtnamajurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 190, -1));

        jtketuajurusan.setText("jTextField3");
        getContentPane().add(jtketuajurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 190, -1));

        jtjmlkelas.setText("jTextField4");
        getContentPane().add(jtjmlkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 190, -1));

        jtcarikdjurusan.setText("jTextField5");
        getContentPane().add(jtcarikdjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 140, -1));

        jbclose.setText("Close");
        jbclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcloseActionPerformed(evt);
            }
        });
        getContentPane().add(jbclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcloseActionPerformed
        // TODO add your handling code here:
        new form_menu_utama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbcloseActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
        // TODO add your handling code here:
         new code_jurusan().bersih(this);
        new code_jurusan().buka_kunci(this);
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsimpanActionPerformed
        // TODO add your handling code here:
         new code_jurusan().simpan(this);
           new code_jurusan().bersih(this);
    }//GEN-LAST:event_jbsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_jurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_jurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_jurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_jurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_jurusan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    public javax.swing.JButton jbclose;
    public javax.swing.JButton jbhapus;
    public javax.swing.JButton jbsimpan;
    public javax.swing.JButton jbtambah;
    public javax.swing.JButton jbubah;
    public javax.swing.JTable jtablejurusan;
    public javax.swing.JTextField jtcarikdjurusan;
    public javax.swing.JTextField jtjmlkelas;
    public javax.swing.JTextField jtkdjurusan;
    public javax.swing.JTextField jtketuajurusan;
    public javax.swing.JTextField jtnamajurusan;
    // End of variables declaration//GEN-END:variables
}
