/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form.pembayaran;

/**
 *
 * @author rpl
 */
public class form_user extends javax.swing.JFrame {

    /**
     * Creates new form form_user
     */
    public form_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtkduser = new javax.swing.JTextField();
        jtnamalengkap = new javax.swing.JTextField();
        jtnotelfon = new javax.swing.JTextField();
        jtusername = new javax.swing.JTextField();
        jppassword = new javax.swing.JPasswordField();
        jbtambah = new javax.swing.JButton();
        jbsimpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jbclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("KD User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel2.setText("Nama Lengkap");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setText("No Telfon");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setText("password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jtkduser.setText("jTextField1");
        getContentPane().add(jtkduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, -1));

        jtnamalengkap.setText("jTextField2");
        getContentPane().add(jtnamalengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 150, -1));

        jtnotelfon.setText("jTextField3");
        getContentPane().add(jtnotelfon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 150, -1));

        jtusername.setText("jTextField4");
        getContentPane().add(jtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 150, -1));

        jppassword.setText("jPasswordField1");
        getContentPane().add(jppassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jbtambah.setText("Tambah");
        getContentPane().add(jbtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jbsimpan.setText("Simpan");
        getContentPane().add(jbsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("USER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 90, 30));

        jbclose.setText("Close");
        jbclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcloseActionPerformed(evt);
            }
        });
        getContentPane().add(jbclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcloseActionPerformed
        // TODO add your handling code here:
        new form_menu_utama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbcloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JButton jbclose;
    public javax.swing.JButton jbsimpan;
    public javax.swing.JButton jbtambah;
    public javax.swing.JPasswordField jppassword;
    public javax.swing.JTextField jtkduser;
    public javax.swing.JTextField jtnamalengkap;
    public javax.swing.JTextField jtnotelfon;
    public javax.swing.JTextField jtusername;
    // End of variables declaration//GEN-END:variables
}
